# Generated by Django 5.0.6 on 2024-05-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_baners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baners',
            new_name='Banner',
        ),
    ]
