# Generated by Django 5.0.6 on 2024-05-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_baners_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='nome_tipo',
            new_name='nome',
        ),
    ]
