# Generated by Django 5.0.6 on 2024-05-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_rename_nome_categoria_categoria_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('cidigo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
