# Generated by Django 5.0.6 on 2024-05-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cor',
            old_name='cidigo',
            new_name='codigo',
        ),
    ]
