# Generated by Django 5.0.6 on 2024-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_rename_cliente_endereco_endereco_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
