# Generated by Django 5.0.6 on 2024-05-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_categoria_slug_tipo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
