# Generated by Django 5.0.6 on 2024-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_categoria_slug_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='imagem_baner',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='links_destino',
            new_name='link_destino',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_cliente',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
