# Generated by Django 5.1.3 on 2024-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='limite_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartao',
            name='score_credito',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
